<?php
/** Departments (Academics). */
return [
    'table' => 'departments',
    'title' => 'Departments',
    'singular' => 'Department',
    'permission' => 'academics',
    'icon' => 'building-2',
    'description' => 'Academic departments and their heads.',
    'select' => "t.*, TRIM(CONCAT_WS(' ', f.title, f.first_name, f.last_name)) AS hod_name, f.photo AS hod_photo,
                 (SELECT COUNT(*) FROM programs p WHERE p.department_id = t.id) AS programs_count,
                 (SELECT COUNT(*) FROM students s WHERE s.department_id = t.id AND s.status = 'active') AS students_count,
                 (SELECT COUNT(*) FROM faculty fc WHERE fc.department_id = t.id AND fc.status = 'active') AS faculty_count",
    'joins' => 'LEFT JOIN faculty f ON f.id = t.hod_faculty_id',
    'search' => ['t.name', 't.code', 't.email'],
    'order' => 't.name ASC',
    'columns' => [
        ['key' => 'name', 'label' => 'Department', 'format' => 'title', 'sub' => 'code', 'sortable' => true],
        ['key' => 'hod_name', 'label' => 'Head of Department', 'format' => 'person', 'image' => 'hod_photo', 'sortable' => 'hod_name'],
        ['key' => 'programs_count', 'label' => 'Programs', 'format' => 'number', 'align' => 'center', 'sortable' => true],
        ['key' => 'faculty_count', 'label' => 'Faculty', 'format' => 'number', 'align' => 'center', 'sortable' => true],
        ['key' => 'students_count', 'label' => 'Students', 'format' => 'number', 'align' => 'center', 'sortable' => true],
        ['key' => 'email', 'label' => 'Email', 'format' => 'email', 'hidden' => true],
        ['key' => 'established_year', 'label' => 'Established', 'format' => 'text', 'hidden' => true, 'sortable' => true],
        ['key' => 'status', 'label' => 'Status', 'format' => 'badge', 'sortable' => true],
    ],
    'filters' => [
        ['key' => 'status', 'label' => 'Status', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
    ],
    'fields' => [
        ['name' => 'name', 'label' => 'Department name', 'type' => 'text', 'required' => true, 'unique' => true, 'col' => 8, 'placeholder' => 'e.g. Department of Management Studies'],
        ['name' => 'code', 'label' => 'Code', 'type' => 'text', 'required' => true, 'unique' => true, 'col' => 4, 'maxlength' => 20, 'rules' => 'alpha_dash', 'placeholder' => 'MGT'],
        ['name' => 'hod_faculty_id', 'label' => 'Head of Department', 'type' => 'select', 'source' => 'faculty'],
        ['name' => 'established_year', 'label' => 'Established year', 'type' => 'number', 'min' => 1900, 'max' => 2100],
        ['name' => 'email', 'label' => 'Email', 'type' => 'email'],
        ['name' => 'phone', 'label' => 'Phone', 'type' => 'tel'],
        ['name' => 'description', 'label' => 'Description', 'type' => 'textarea', 'rows' => 3],
        ['name' => 'image', 'label' => 'Cover image', 'type' => 'image', 'folder' => 'departments'],
        ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'required' => true, 'default' => 'active', 'options' => ['active' => 'Active', 'inactive' => 'Inactive']],
    ],
    'bulk' => ['delete' => true, 'status' => ['active', 'inactive']],
    'import' => true,
    'form' => ['size' => 'lg'],
];
