import {
  ArrowRight,
  Award,
  BadgeCheck,
  BadgeIndianRupee,
  BedDouble,
  BookMarked,
  BookOpen,
  Briefcase,
  BriefcaseBusiness,
  Building,
  Building2,
  Bus,
  Calculator,
  CalendarCheck,
  CalendarDays,
  ChartColumn,
  Check,
  CircleCheck,
  CircleCheckBig,
  CirclePlay,
  ClipboardCheck,
  Clock,
  CodeXml,
  Compass,
  Cpu,
  Download,
  Dumbbell,
  FileCheck,
  FileText,
  FlaskConical,
  Globe,
  GraduationCap,
  HandHeart,
  Handshake,
  Headset,
  Heart,
  Image,
  IndianRupee,
  Landmark,
  Laptop,
  LayoutGrid,
  Leaf,
  Library,
  Lightbulb,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  Microscope,
  Monitor,
  Newspaper,
  Palette,
  PenTool,
  Phone,
  Play,
  Presentation,
  Rocket,
  Scale,
  School,
  Search,
  Send,
  ShieldCheck,
  Sparkles,
  Star,
  Target,
  Trees,
  TrendingUp,
  Trophy,
  Upload,
  User,
  UserRound,
  Users,
  UsersRound,
  Wallet,
  Wifi,
  type LucideIcon,
} from 'lucide-react';

/**
 * Curated icon set for islands — props coming from PHP reference icons by their lucide kebab-case name
 * (the same names the PHP icon() helper uses). Unknown names fall back to a neutral sparkle.
 * Add icons here when a page needs a new one (keep the list lean: every entry ships in the icons chunk).
 */
const ICONS: Record<string, LucideIcon> = {
  'arrow-right': ArrowRight,
  award: Award,
  'badge-check': BadgeCheck,
  'badge-indian-rupee': BadgeIndianRupee,
  'bed-double': BedDouble,
  'book-marked': BookMarked,
  'book-open': BookOpen,
  briefcase: Briefcase,
  'briefcase-business': BriefcaseBusiness,
  building: Building,
  'building-2': Building2,
  bus: Bus,
  calculator: Calculator,
  'calendar-check': CalendarCheck,
  'calendar-days': CalendarDays,
  'chart-column': ChartColumn,
  check: Check,
  'circle-check': CircleCheck,
  'circle-check-big': CircleCheckBig,
  'circle-play': CirclePlay,
  'clipboard-check': ClipboardCheck,
  clock: Clock,
  'code-xml': CodeXml,
  compass: Compass,
  cpu: Cpu,
  download: Download,
  dumbbell: Dumbbell,
  'file-check': FileCheck,
  'file-text': FileText,
  'flask-conical': FlaskConical,
  globe: Globe,
  'graduation-cap': GraduationCap,
  'hand-heart': HandHeart,
  handshake: Handshake,
  headset: Headset,
  heart: Heart,
  image: Image,
  'indian-rupee': IndianRupee,
  landmark: Landmark,
  laptop: Laptop,
  'layout-grid': LayoutGrid,
  leaf: Leaf,
  library: Library,
  lightbulb: Lightbulb,
  mail: Mail,
  'map-pin': MapPin,
  megaphone: Megaphone,
  'message-circle': MessageCircle,
  microscope: Microscope,
  monitor: Monitor,
  newspaper: Newspaper,
  palette: Palette,
  'pen-tool': PenTool,
  phone: Phone,
  play: Play,
  presentation: Presentation,
  rocket: Rocket,
  scale: Scale,
  school: School,
  search: Search,
  send: Send,
  'shield-check': ShieldCheck,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  trees: Trees,
  'trending-up': TrendingUp,
  trophy: Trophy,
  upload: Upload,
  user: User,
  'user-round': UserRound,
  users: Users,
  'users-round': UsersRound,
  wallet: Wallet,
  wifi: Wifi,
};

export function Icon({ name, className, strokeWidth = 2 }: { name?: string | null; className?: string; strokeWidth?: number }) {
  if (!name) return null;
  const Cmp = ICONS[name] ?? Sparkles;
  return <Cmp className={className} strokeWidth={strokeWidth} aria-hidden="true" focusable="false" />;
}
