-- =====================================================================
-- 04 Students: students, parents/guardians, academic history, documents
-- =====================================================================

CREATE TABLE students (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  student_uid VARCHAR(30) NOT NULL COMMENT 'Student ID e.g. GIMT26BBA0001',
  admission_no VARCHAR(30) NOT NULL,
  roll_no VARCHAR(30) NULL,
  enrollment_no VARCHAR(40) NULL COMMENT 'university enrolment number',
  user_id INT UNSIGNED NULL,
  admission_id INT UNSIGNED NULL COMMENT 'source admission application (FK in 05_admissions.sql)',
  first_name VARCHAR(80) NOT NULL,
  middle_name VARCHAR(80) NULL,
  last_name VARCHAR(80) NULL,
  photo VARCHAR(255) NULL,
  gender VARCHAR(10) NOT NULL COMMENT 'male|female|other',
  dob DATE NULL,
  blood_group VARCHAR(5) NULL,
  category VARCHAR(20) NULL COMMENT 'General|OBC|SC|ST|EWS',
  religion VARCHAR(40) NULL,
  nationality VARCHAR(60) NULL DEFAULT 'Indian',
  aadhaar_no VARCHAR(20) NULL,
  mobile VARCHAR(20) NOT NULL,
  email VARCHAR(190) NULL,
  whatsapp VARCHAR(20) NULL,
  address VARCHAR(255) NULL,
  city VARCHAR(80) NULL,
  state VARCHAR(80) NULL,
  country VARCHAR(80) NULL DEFAULT 'India',
  pincode VARCHAR(12) NULL,
  permanent_address VARCHAR(255) NULL,
  father_name VARCHAR(150) NULL,
  mother_name VARCHAR(150) NULL,
  guardian_name VARCHAR(150) NULL,
  guardian_relation VARCHAR(40) NULL,
  guardian_phone VARCHAR(20) NULL,
  emergency_contact_name VARCHAR(150) NULL,
  emergency_contact_phone VARCHAR(20) NULL,
  department_id INT UNSIGNED NULL,
  program_id INT UNSIGNED NOT NULL,
  course_id INT UNSIGNED NULL COMMENT 'specialization',
  batch_id INT UNSIGNED NULL,
  current_semester TINYINT UNSIGNED NOT NULL DEFAULT 1,
  section_id INT UNSIGNED NULL,
  academic_session_id INT UNSIGNED NULL COMMENT 'session of admission',
  admission_date DATE NULL,
  admission_type VARCHAR(20) NULL DEFAULT 'regular' COMMENT 'regular|lateral|management|scholarship',
  previous_qualification VARCHAR(150) NULL,
  previous_percentage DECIMAL(5,2) NULL,
  is_hosteller TINYINT(1) NOT NULL DEFAULT 0,
  uses_transport TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT 'active|inactive|suspended|dropped|graduated|alumni',
  status_reason VARCHAR(255) NULL,
  remarks TEXT NULL,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_students_uid (student_uid),
  UNIQUE KEY uq_students_admission_no (admission_no),
  UNIQUE KEY uq_students_email (email),
  KEY idx_students_program (program_id, current_semester, section_id),
  KEY idx_students_department (department_id),
  KEY idx_students_session (academic_session_id),
  KEY idx_students_status (status),
  KEY idx_students_name (first_name, last_name),
  CONSTRAINT fk_students_department FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL,
  CONSTRAINT fk_students_program FOREIGN KEY (program_id) REFERENCES programs(id),
  CONSTRAINT fk_students_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE SET NULL,
  CONSTRAINT fk_students_batch FOREIGN KEY (batch_id) REFERENCES batches(id) ON DELETE SET NULL,
  CONSTRAINT fk_students_section FOREIGN KEY (section_id) REFERENCES sections(id) ON DELETE SET NULL,
  CONSTRAINT fk_students_session FOREIGN KEY (academic_session_id) REFERENCES academic_sessions(id) ON DELETE SET NULL,
  CONSTRAINT fk_students_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE student_parents (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  student_id INT UNSIGNED NOT NULL,
  relation VARCHAR(20) NOT NULL COMMENT 'father|mother|guardian|other',
  name VARCHAR(150) NOT NULL,
  phone VARCHAR(20) NULL,
  email VARCHAR(190) NULL,
  occupation VARCHAR(100) NULL,
  annual_income DECIMAL(12,2) NULL,
  address VARCHAR(255) NULL,
  is_emergency_contact TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_parents_student (student_id),
  CONSTRAINT fk_parents_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Semester-wise academic history (promotion records)
CREATE TABLE student_academic (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  student_id INT UNSIGNED NOT NULL,
  academic_session_id INT UNSIGNED NULL,
  program_id INT UNSIGNED NOT NULL,
  semester_no TINYINT UNSIGNED NOT NULL,
  section_id INT UNSIGNED NULL,
  roll_no VARCHAR(30) NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'studying' COMMENT 'studying|promoted|detained|completed|dropped',
  sgpa DECIMAL(4,2) NULL,
  cgpa DECIMAL(4,2) NULL,
  attendance_percent DECIMAL(5,2) NULL,
  promoted_at DATETIME NULL,
  promoted_by INT UNSIGNED NULL,
  remarks VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_student_academic (student_id, semester_no, academic_session_id),
  CONSTRAINT fk_sa_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  CONSTRAINT fk_sa_session FOREIGN KEY (academic_session_id) REFERENCES academic_sessions(id) ON DELETE SET NULL,
  CONSTRAINT fk_sa_program FOREIGN KEY (program_id) REFERENCES programs(id),
  CONSTRAINT fk_sa_section FOREIGN KEY (section_id) REFERENCES sections(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE student_documents (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  student_id INT UNSIGNED NOT NULL,
  doc_type VARCHAR(40) NOT NULL COMMENT '10th_marksheet|12th_marksheet|graduation|id_proof|photo|transfer_certificate|migration|caste_certificate|income_certificate|other',
  title VARCHAR(190) NOT NULL,
  file_path VARCHAR(255) NOT NULL COMMENT 'private storage path',
  original_name VARCHAR(190) NULL,
  mime VARCHAR(100) NULL,
  size_bytes INT UNSIGNED NULL,
  is_verified TINYINT(1) NOT NULL DEFAULT 0,
  verified_by INT UNSIGNED NULL,
  verified_at DATETIME NULL,
  uploaded_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_sdocs_student (student_id),
  CONSTRAINT fk_sdocs_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
