-- =====================================================================
-- 05 Admissions: enquiries, applications, documents, follow-ups, history
-- Pipeline stages: enquiry -> application -> document_verification ->
--   entrance_interview -> approval -> fee_payment -> confirmed
--   (terminal: rejected | withdrawn)
-- =====================================================================

CREATE TABLE enquiries (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(190) NULL,
  phone VARCHAR(20) NOT NULL,
  city VARCHAR(80) NULL,
  program_id INT UNSIGNED NULL,
  program_interest VARCHAR(190) NULL COMMENT 'free text when program not chosen',
  source VARCHAR(30) NOT NULL DEFAULT 'website' COMMENT 'website|walk_in|phone|social_media|referral|campaign|education_fair|whatsapp|other',
  message TEXT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'new' COMMENT 'new|contacted|interested|not_interested|converted|closed',
  priority VARCHAR(10) NOT NULL DEFAULT 'medium' COMMENT 'low|medium|high',
  assigned_to INT UNSIGNED NULL,
  follow_up_date DATE NULL,
  notes TEXT NULL,
  admission_id INT UNSIGNED NULL COMMENT 'set when converted to application',
  utm_source VARCHAR(100) NULL,
  utm_campaign VARCHAR(100) NULL,
  ip_address VARCHAR(45) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_enquiries_status (status),
  KEY idx_enquiries_created (created_at),
  KEY idx_enquiries_program (program_id),
  CONSTRAINT fk_enquiries_program FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE SET NULL,
  CONSTRAINT fk_enquiries_assigned FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE admissions (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  application_no VARCHAR(30) NOT NULL,
  enquiry_id INT UNSIGNED NULL,
  academic_session_id INT UNSIGNED NULL,
  program_id INT UNSIGNED NOT NULL,
  course_id INT UNSIGNED NULL,
  first_name VARCHAR(80) NOT NULL,
  middle_name VARCHAR(80) NULL,
  last_name VARCHAR(80) NULL,
  photo VARCHAR(255) NULL,
  gender VARCHAR(10) NULL,
  dob DATE NULL,
  blood_group VARCHAR(5) NULL,
  category VARCHAR(20) NULL,
  nationality VARCHAR(60) NULL DEFAULT 'Indian',
  email VARCHAR(190) NULL,
  phone VARCHAR(20) NOT NULL,
  whatsapp VARCHAR(20) NULL,
  address VARCHAR(255) NULL,
  city VARCHAR(80) NULL,
  state VARCHAR(80) NULL,
  country VARCHAR(80) NULL DEFAULT 'India',
  pincode VARCHAR(12) NULL,
  father_name VARCHAR(150) NULL,
  mother_name VARCHAR(150) NULL,
  guardian_phone VARCHAR(20) NULL,
  previous_qualification VARCHAR(150) NULL,
  previous_institution VARCHAR(190) NULL,
  previous_board VARCHAR(100) NULL,
  previous_percentage DECIMAL(5,2) NULL,
  passing_year SMALLINT UNSIGNED NULL,
  entrance_exam VARCHAR(60) NULL,
  entrance_score DECIMAL(6,2) NULL,
  interview_date DATETIME NULL,
  interview_score DECIMAL(5,2) NULL,
  interview_remarks VARCHAR(500) NULL,
  source VARCHAR(30) NOT NULL DEFAULT 'website' COMMENT 'same values as enquiries.source',
  stage VARCHAR(30) NOT NULL DEFAULT 'application' COMMENT 'enquiry|application|document_verification|entrance_interview|approval|fee_payment|confirmed|rejected|withdrawn',
  counselling_notes TEXT NULL,
  rejection_reason VARCHAR(255) NULL,
  assigned_to INT UNSIGNED NULL COMMENT 'counsellor / admission officer',
  admission_fee DECIMAL(12,2) NULL,
  fee_paid DECIMAL(12,2) NOT NULL DEFAULT 0,
  payment_id INT UNSIGNED NULL COMMENT 'payments.id of admission fee',
  offer_letter_no VARCHAR(40) NULL,
  offer_issued_at DATETIME NULL,
  approved_by INT UNSIGNED NULL,
  approved_at DATETIME NULL,
  student_id INT UNSIGNED NULL COMMENT 'set when converted to student',
  converted_at DATETIME NULL,
  ip_address VARCHAR(45) NULL,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_admissions_application_no (application_no),
  KEY idx_admissions_stage (stage),
  KEY idx_admissions_program (program_id),
  KEY idx_admissions_session (academic_session_id),
  KEY idx_admissions_created (created_at),
  CONSTRAINT fk_admissions_enquiry FOREIGN KEY (enquiry_id) REFERENCES enquiries(id) ON DELETE SET NULL,
  CONSTRAINT fk_admissions_session FOREIGN KEY (academic_session_id) REFERENCES academic_sessions(id) ON DELETE SET NULL,
  CONSTRAINT fk_admissions_program FOREIGN KEY (program_id) REFERENCES programs(id),
  CONSTRAINT fk_admissions_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE SET NULL,
  CONSTRAINT fk_admissions_assigned FOREIGN KEY (assigned_to) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_admissions_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE enquiries ADD CONSTRAINT fk_enquiries_admission FOREIGN KEY (admission_id) REFERENCES admissions(id) ON DELETE SET NULL;
ALTER TABLE students ADD CONSTRAINT fk_students_admission FOREIGN KEY (admission_id) REFERENCES admissions(id) ON DELETE SET NULL;

CREATE TABLE admission_documents (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  admission_id INT UNSIGNED NOT NULL,
  doc_type VARCHAR(40) NOT NULL COMMENT 'photo|10th_marksheet|12th_marksheet|graduation|id_proof|transfer_certificate|migration|caste_certificate|other',
  file_path VARCHAR(255) NOT NULL COMMENT 'private storage path',
  original_name VARCHAR(190) NULL,
  mime VARCHAR(100) NULL,
  size_bytes INT UNSIGNED NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT 'pending|verified|rejected',
  remarks VARCHAR(255) NULL,
  verified_by INT UNSIGNED NULL,
  verified_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_adocs_admission (admission_id),
  CONSTRAINT fk_adocs_admission FOREIGN KEY (admission_id) REFERENCES admissions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE admission_followups (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  admission_id INT UNSIGNED NULL,
  enquiry_id INT UNSIGNED NULL,
  type VARCHAR(20) NOT NULL DEFAULT 'call' COMMENT 'call|email|sms|whatsapp|meeting|campus_visit|note',
  notes TEXT NOT NULL,
  outcome VARCHAR(30) NULL COMMENT 'interested|not_reachable|callback|not_interested|visited|applied',
  next_followup_date DATE NULL,
  created_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_followups_admission (admission_id),
  KEY idx_followups_enquiry (enquiry_id),
  KEY idx_followups_next (next_followup_date),
  CONSTRAINT fk_followups_admission FOREIGN KEY (admission_id) REFERENCES admissions(id) ON DELETE CASCADE,
  CONSTRAINT fk_followups_enquiry FOREIGN KEY (enquiry_id) REFERENCES enquiries(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE admission_stage_history (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  admission_id INT UNSIGNED NOT NULL,
  from_stage VARCHAR(30) NULL,
  to_stage VARCHAR(30) NOT NULL,
  remarks VARCHAR(500) NULL,
  changed_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_ash_admission (admission_id),
  CONSTRAINT fk_ash_admission FOREIGN KEY (admission_id) REFERENCES admissions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
